defmodule Tunez.Repo.Migrations.AddSecretNicknameToArtists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :encrypted_secret_nickname, :binary
    end
  end

  def down do
    alter table(:artists) do
      remove :encrypted_secret_nickname
    end
  end
end
